'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import AppLayout from '@/components/AppLayout'
import BomAnalyzeContent from '@/components/BomAnalyzeContent'
import { DeleteBomButton } from '@/components/DeleteBomButton'
import { ExportButtons } from '@/components/ExportButtons'
import { useAuth } from '@/components/AuthProvider'
import { ConfidenceBadge } from '@/components/StatusBadge'
import { Link } from '@/lib/navigation'
import { getBom } from '@/lib/api'
import type { AnalyzeResult } from '@/lib/types'

function PlaceholderSection({ title, description }: { title: string; description: string }) {
  return (
    <section className="rounded-xl border border-dashed border-[#d6deea] bg-[#fafbfc] p-5">
      <h2 className="text-[13px] font-semibold text-[#0f1b2d]">{title}</h2>
      <p className="mt-1 text-[12px] text-[#7a8598]">{description}</p>
      <p className="mt-3 text-[11px] font-medium uppercase tracking-wide text-[#98a3b6]">Coming soon</p>
    </section>
  )
}

function BackToBoms() {
  return (
    <Link
      href="/dashboard?tab=boms"
      className="inline-flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg border border-[#d6deea] bg-white text-[#4f5d73] transition-colors hover:border-[#0062ff] hover:text-[#0062ff]"
      aria-label="Back to BOMs"
      title="Back to BOMs"
    >
      <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
      </svg>
    </Link>
  )
}

type BomResultPageProps = {
  id: string
}

export default function BomResultPage({ id }: BomResultPageProps) {
  const router = useRouter()
  const { user, loading: authLoading } = useAuth()
  const [result, setResult] = useState<AnalyzeResult | null>(null)
  const [loaded, setLoaded] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (authLoading) return
    if (!user) {
      router.push('/login')
      return
    }
    if (!id) {
      setLoaded(true)
      return
    }

    let cancelled = false
    setError(null)

    getBom(id)
      .then((record) => {
        if (!cancelled) setResult(record.analyze)
      })
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : 'Failed to load BOM')
      })
      .finally(() => {
        if (!cancelled) setLoaded(true)
      })

    return () => {
      cancelled = true
    }
  }, [authLoading, user, id, router])

  if (!loaded || authLoading) return null

  if (!result) {
    return (
      <AppLayout>
        <div className="flex flex-1 flex-col items-center justify-center p-6 text-center">
          <h1 className="text-[18px] font-semibold text-[#0f1b2d]">{error ? 'Could not load BOM' : 'BOM not found'}</h1>
          <p className="mt-2 text-[13px] text-[#7a8598]">
            {error ?? 'This BOM may not exist in your account, or you may not have access to it.'}
          </p>
          <Link
            href="/dashboard?tab=boms"
            className="mt-6 rounded-lg bg-[#0062ff] px-4 py-2 text-[13px] font-medium text-white hover:bg-[#0050e6]"
          >
            Back to BOMs
          </Link>
        </div>
      </AppLayout>
    )
  }

  return (
    <AppLayout>
      <div className="flex h-14 flex-shrink-0 items-center justify-between border-b border-[#d6deea] bg-white px-6">
        <div className="flex min-w-0 items-center gap-3">
          <BackToBoms />
          <h1 className="truncate text-[15px] font-semibold text-[#0f1b2d]">{result.source_filename}</h1>
          {result.sheet_name && (
            <span className="rounded border border-[#d6deea] bg-[#f4f6f9] px-2 py-0.5 font-mono text-[11px] text-[#7a8598]">
              {result.sheet_name}
            </span>
          )}
          <ConfidenceBadge value={result.mapping_confidence} />
        </div>
        <div className="flex items-center gap-2">
          <ExportButtons result={result} />
          <DeleteBomButton
            bomId={id}
            bomName={result.source_filename}
            redirectTo="/dashboard?tab=boms"
          />
        </div>
      </div>

      <div className="flex-1 overflow-auto p-6">
        <div className="mx-auto max-w-7xl space-y-6">
          <div className="grid grid-cols-2 gap-4">
            <PlaceholderSection
              title="Alternate Parts"
              description="Vetted drop-in alternatives, ranked by availability and cost — ready when you need them."
            />
            <PlaceholderSection
              title="Action Plan"
              description="Prioritized actions: who to contact, what to order, and when — generated by the Prokuro agent."
            />
          </div>

          <BomAnalyzeContent result={result} />
        </div>
      </div>
    </AppLayout>
  )
}
