'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import DashboardShell from '@/components/DashboardShell'
import { AnalyzeTable } from '@/components/BomTable'
import { DeleteBomButton } from '@/components/DeleteBomButton'
import { ExportButtons } from '@/components/ExportButtons'
import { useAuth } from '@/components/AuthProvider'
import { ConfidenceBadge } from '@/components/StatusBadge'
import { AnalyzeSummaryCards } from '@/components/SummaryCards'
import { Link } from '@/lib/navigation'
import { getBom } from '@/lib/api'
import type { AnalyzeResult } from '@/lib/types'

function PlaceholderSection({ title, description }: { title: string; description: string }) {
  return (
    <section className="rounded-xl border border-dashed border-hairline bg-canvas p-5">
      <h2 className="text-[13px] font-semibold text-ink">{title}</h2>
      <p className="mt-1 text-[12px] text-ink-subtle">{description}</p>
      <p className="mt-3 text-[11px] font-medium uppercase tracking-wide text-ink-tertiary">Coming soon</p>
    </section>
  )
}

function BackToBoms() {
  return (
    <Link
      href="/dashboard?tab=boms"
      className="inline-flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg border border-hairline bg-canvas text-ink-muted transition-colors hover:border-primary hover:text-primary"
      aria-label="Back to BOMs"
      title="Back to BOMs"
    >
      <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
      </svg>
    </Link>
  )
}

type BomResultPageProps = {
  id: string
}

export default function BomResultPage({ id }: BomResultPageProps) {
  const router = useRouter()
  const { user, loading: authLoading } = useAuth()
  const [result, setResult] = useState<AnalyzeResult | null>(null)
  const [loaded, setLoaded] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (authLoading) return
    if (!user) {
      router.push('/login')
      return
    }
    if (!id) {
      setLoaded(true)
      return
    }

    let cancelled = false
    setError(null)

    getBom(id)
      .then((record) => {
        if (!cancelled) setResult(record.analyze)
      })
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : 'Failed to load BOM')
      })
      .finally(() => {
        if (!cancelled) setLoaded(true)
      })

    return () => {
      cancelled = true
    }
  }, [authLoading, user, id, router])

  if (!loaded || authLoading) return null

  if (!result) {
    return (
      <DashboardShell activeTab="boms">
        <div className="flex flex-1 flex-col items-center justify-center p-6 text-center">
          <h1 className="text-[18px] font-semibold text-ink">{error ? 'Could not load BOM' : 'BOM not found'}</h1>
          <p className="mt-2 text-[13px] text-ink-subtle">
            {error ?? 'This BOM may not exist in your account, or you may not have access to it.'}
          </p>
          <Link
            href="/dashboard?tab=boms"
            className="mt-6 rounded-lg bg-primary px-4 py-2 text-[13px] font-medium text-white hover:bg-primary-hover"
          >
            Back to BOMs
          </Link>
        </div>
      </DashboardShell>
    )
  }

  return (
    <DashboardShell activeTab="boms">
      <div className="flex h-14 flex-shrink-0 items-center justify-between border-b border-hairline bg-canvas px-6">
        <div className="flex min-w-0 items-center gap-3">
          <BackToBoms />
          <h1 className="truncate text-[15px] font-semibold text-ink">{result.source_filename}</h1>
          {result.sheet_name && (
            <span className="rounded border border-hairline bg-surface-1 px-2 py-0.5 font-mono text-[11px] text-ink-subtle">
              {result.sheet_name}
            </span>
          )}
          <ConfidenceBadge value={result.mapping_confidence} />
        </div>
        <div className="flex items-center gap-2">
          <ExportButtons result={result} />
          <DeleteBomButton
            bomId={id}
            bomName={result.source_filename}
            redirectTo="/dashboard?tab=boms"
          />
        </div>
      </div>

      <div className="flex-1 overflow-auto p-6">
        <div className="mx-auto max-w-7xl space-y-6">
          <AnalyzeSummaryCards result={result} />

          <div className="grid grid-cols-2 gap-4">
            <PlaceholderSection
              title="Alternate Parts"
              description="Vetted drop-in alternatives, ranked by availability and cost — ready when you need them."
            />
            <PlaceholderSection
              title="Action Plan"
              description="Prioritized actions: who to contact, what to order, and when — generated by the Prokuro agent."
            />
          </div>

          <section>
            <h2 className="mb-3 text-[13px] font-semibold text-ink">BOM Lines</h2>
            <AnalyzeTable result={result} />
          </section>
        </div>
      </div>
    </DashboardShell>
  )
}
